on:
  push:
    branches: [master, main]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: vercel build --token $VERCEL_TOKEN --prod
      - run: vercel deploy --prebuilt --token $VERCEL_TOKEN --prod
